# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: gotenberg-client
  version: "0.13.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gotenberg_client-${{ version }}.tar.gz
  sha256: 0fb2425d0e1e4f143285ecde90f7687f4d234d2b23316f5d42015337d336a4ab

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.27.0,<1.28.dev0
    - pip
  run:
    - python >=${{ python_min }},<4
    - httpx >=0.27
    - typing_extensions

tests:
  - python:
      imports:
        - gotenberg_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A Python client for interfacing with the Gotenberg API
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/stumpylog/gotenberg-client/

extra:
  recipe-maintainers:
    - rxm7706
